apiVersion: v1
kind: Service
metadata:
  name: lgtmspring-service
spec:
  selector:
    app: lgtmspring
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer